// ALBUM
export const CREATE_ALBUM_CLEAR        = 'CREATE_ALBUM_CLEAR';
export const CREATE_ALBUM_DONE         = 'CREATE_ALBUM_DONE';
export const CREATE_ALBUM_START        = 'CREATE_ALBUM_START';
export const CREATE_ALBUM_ERROR        = 'CREATE_ALBUM_ERROR';
export const UPDATE_ALBUM_DONE         = 'UPDATE_ALBUM_DONE';
export const UPDATE_ALBUM_START        = 'UPDATE_ALBUM_START';
export const UPDATE_ALBUM_ERROR        = 'UPDATE_ALBUM_ERROR';
export const DELETE_ALBUM_DONE         = 'DELETE_ALBUM_DONE';
export const DELETE_ALBUM_START        = 'DELETE_ALBUM_START';
export const DELETE_ALBUM_ERROR        = 'DELETE_ALBUM_ERROR';
export const FETCH_ALL_ALBUMS_DONE     = 'FETCH_ALL_ALBUMS_DONE';
export const FETCH_ALL_ALBUMS_START    = 'FETCH_ALL_ALBUMS_START';
export const FETCH_ALL_ALBUMS_ERROR    = 'FETCH_ALL_ALBUMS_ERROR';
export const FETCH_PUBLIC_ALBUMS_DONE  = 'FETCH_PUBLIC_ALBUMS_DONE';
export const FETCH_PUBLIC_ALBUMS_START = 'FETCH_PUBLIC_ALBUMS_START';
export const FETCH_PUBLIC_ALBUMS_ERROR = 'FETCH_PUBLIC_ALBUMS_ERROR';
export const SET_PUBLIC_ALBUMS         = 'SET_PUBLIC_ALBUMS';
export const SET_ALBUM_ID              = 'SET_ALBUM_ID';
export const SET_ALBUM_FILTER          = 'SET_ALBUM_FILTER';

// PICTURES
export const FETCH_ALL_PICTURES_DONE     = 'FETCH_ALL_PICTURES_DONE';
export const FETCH_ALL_PICTURES_START    = 'FETCH_ALL_PICTURES_START';
export const FETCH_ALL_PICTURES_ERROR    = 'FETCH_ALL_PICTURES_ERROR';
export const FETCH_PUBLIC_PICTURES_DONE  = 'FETCH_PUBLIC_PICTURES_DONE';
export const FETCH_PUBLIC_PICTURES_START = 'FETCH_PUBLIC_PICTURES_START';
export const FETCH_PUBLIC_PICTURES_ERROR = 'FETCH_PUBLIC_PICTURES_ERROR';
export const CREATE_PICTURE_DONE         = 'CREATE_PICTURE_DONE';
export const CREATE_PICTURE_START        = 'CREATE_PICTURE_START';
export const CREATE_PICTURE_ERROR        = 'CREATE_PICTURE_ERROR';
export const CREATE_PICTURE_CLEAR        = 'CREATE_PICTURE_CLEAR';
export const UPDATE_PICTURE_DONE         = 'UPDATE_PICTURE_DONE';
export const UPDATE_PICTURE_START        = 'UPDATE_PICTURE_START';
export const UPDATE_PICTURE_ERROR        = 'UPDATE_PICTURE_ERROR';
export const DELETE_PICTURE_DONE         = 'DELETE_PICTURE_DONE';
export const DELETE_PICTURE_START        = 'DELETE_PICTURE_START';
export const DELETE_PICTURE_ERROR        = 'DELETE_PICTURE_ERROR';

// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_DONE  = 'AUTH_DONE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT     = 'LOGOUT';

// DOWNLOAD
export const DOWNLOAD_PICTURE_START    = 'DOWNLOAD_PICTURE_START';
export const DOWNLOAD_PICTURE_DONE     = 'DOWNLOAD_PICTURE_DONE';
export const DOWNLOAD_PICTURE_ERROR    = 'DOWNLOAD_PICTURE_ERROR';
export const DOWNLOAD_ALBUM_START      = 'DOWNLOAD_ALBUM_START';
export const DOWNLOAD_ALBUM_DONE       = 'DOWNLOAD_ALBUM_DONE';
export const DOWNLOAD_ALBUM_ERROR      = 'DOWNLOAD_ALBUM_ERROR';
export const DOWNLOAD_STATUS_START     = 'DOWNLOAD_STATUS_START';
export const DOWNLOAD_STATUS_DONE      = 'DOWNLOAD_STATUS_DONE';
export const DOWNLOAD_STATUS_ERROR     = 'DOWNLOAD_STATUS_ERROR';
export const DOWNLOAD_REQ_START        = 'DOWNLOAD_REQ_START';
export const DOWNLOAD_REQ_DONE         = 'DOWNLOAD_REQ_DONE';
export const DOWNLOAD_REQ_ERROR        = 'DOWNLOAD_REQ_ERROR';
export const DOWNLOAD_SET_START        = 'DOWNLOAD_SET_START';
export const DOWNLOAD_SET_DONE         = 'DOWNLOAD_SET_DONE';
export const DOWNLOAD_SET_ERROR        = 'DOWNLOAD_SET_ERROR';
export const DOWNLOAD_SET_INDOWNLOAD   = 'DOWNLOAD_SET_INDOWNLOAD';
